// Code generated by Mockery. DO NOT EDIT.

package mocks

import (
	"finance-api/internal/model"
	"github.com/stretchr/testify/mock"
)

type TransactionRepository struct {
	mock.Mock
}

func (m *TransactionRepository) FetchLastTransactions(userID int, limit int) ([]model.Transaction, error) {
    args := m.Called(userID, limit)
    if args.Get(0) == nil {
        return nil, args.Error(1)
    }
    return args.Get(0).([]model.Transaction), args.Error(1)
}
